[tool.black]
line-length = 110

[tool.pytest.ini_options]
minversion = "6.0"
addopts = '''
  -v
  -rs
  --strict-config
  --strict-markers
  --showlocals
  --black
  --flake8
  --isort
  --junitxml=junit/test-results.xml
  --cov=.
  --cov-branch
  --cov-report xml:cov.xml
  --cov-report html:htmlcov
  --cov-report term
  --ignore=strava
'''

[tool.coverage.run]
branch=true
omit = [
  '**/test_*.py',
  '**/__init__.py',
  '.venv/**/*.py',
  'test/',
  'cli/__main__.py',
  'core/*.py',
  'strava/',
  'tasks.py'
]


[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 110
import_heading_stdlib='Standard Library'
import_heading_thirdparty='Third Party Libraries'
import_heading_firstparty='Our Libraries'
